### PR TITLE
Gradle changes

### PR DESCRIPTION
**Pull request by ppamorim**
I've seen some inconsistencies at these gradle files and this is a little fix.

### CODE REVIEW

**Comment by willbailey** [comment]
This is failing in Travis CI. Can you investigate?

**Comment by willbailey** [comment]
Per the travis logs:

* What went wrong:
A problem occurred configuring root project 'rebound'.
> failed to find target android-22 : /home/travis/build/facebook/rebound/android-sdk-linux

You need to update .travis.yml as well to install the v22 sdk if you want to make this change.

**Comment by ppamorim** [comment]
Yes, I'll fix it.

**Comment by ppamorim** [comment]
Works like a charm

**Comment by willbailey** [comment]
Thanks

**Pull request merged**
